#!/bin/sh

set -o errexit

cd -- "$(dirname -- "$0")" && cd ..

if [ -n "${1:-}" ]; then
    switch-php "$1"
fi

if [ -n "${2:-}" ]; then
    switch-composer "$2"
fi

composer valid --strict

ccm-service start db

TEST_PHPUNIT_BIN=../../concrete/vendor/bin/phpunit
if [ -f "$TEST_PHPUNIT_BIN" ]; then
    composerpkg --no-interaction --ansi update --prefer-dist --optimize-autoloader --no-dev
else
    TEST_PHPUNIT_BIN=./vendor/bin/phpunit
    cp composer.json composer.json.original
    composer --no-interaction --ansi require --no-update concrete5/core:$(c5 c5:info | grep 'Core Version' | cut -d' ' -f4)
    composerpkg --no-interaction --ansi update --prefer-dist --optimize-autoloader
    mv composer.json.original composer.json
fi

c5 c5:package:install acme

"$TEST_PHPUNIT_BIN"
